 - name: Setup Node.js environment
    uses: actions/setup-node@v4.3.0
    with:
    always-auth: false  # Set always-auth in npmrc.
    node-version: '14.x'  # Specify the Node.js version to use.
    architecture: 'x64'  # Target architecture for Node to use.
    check-latest: true  # Check for the latest available version that satisfies the version spec.
    registry-url: 'https://registry.npmjs.org'  # Registry URL for npm.
    cache: 'npm'  # Specify the package manager for caching.
    cache-dependency-path: '**/package-lock.json'  # Path to the dependency file for caching.
